export const GET_PRODUCTS = 'products/GET_PRODUCTS';
export const GET_PRODUCTS_LOADING = 'products/GET_PRODUCTS_LOADING';
export const GET_PRODUCTS_ERROR = 'products/GET_PRODUCTS_ERROR';

export const GET_PRODUCT = 'products/GET_PRODUCT';
export const GET_PRODUCT_LOADING = 'products/GET_PRODUCT_LOADING';
export const GET_PRODUCT_ERROR = 'products/GET_PRODUCT_ERROR';

export const ADD_PRODUCT = 'products/ADD_PRODUCT';
export const ADD_PRODUCT_LOADING = 'products/ADD_PRODUCT_LOADING';
export const ADD_PRODUCT_ERROR = 'products/ADD_PRODUCT_ERROR';

export const UPDATE_PRODUCT = 'products/UPDATE_PRODUCT';
export const UPDATE_PRODUCT_LOADING = 'products/UPDATE_PRODUCT_LOADING';
export const UPDATE_PRODUCT_ERROR = 'products/UPDATE_PRODUCT_ERROR';

export const DELETE_PRODUCT = 'products/DELETE_PRODUCT';
export const DELETE_PRODUCT_LOADING = 'products/DELETE_PRODUCT_LOADING';
export const DELETE_PRODUCT_ERROR = 'products/DELETE_PRODUCT_ERROR';

export const GET_PRODUCTS_BY_SEARCH = 'products/GET_PRODUCTS_BY_SEARCH';
export const GET_PRODUCTS_BY_SEARCH_LOADING = 'products/GET_PRODUCTS_BY_SEARCH_LOADING';
export const GET_PRODUCTS_BY_SEARCH_ERROR = 'products/GET_PRODUCTS_BY_SEARCH_ERROR';

export const GET_PRODUCTS_BY_FILTER = 'products/GET_PRODUCTS_BY_FILTER';
export const GET_PRODUCTS_BY_FILTER_LOADING = 'products/GET_PRODUCTS_BY_FILTER_LOADING';
export const GET_PRODUCTS_BY_FILTER_ERROR = 'products/GET_PRODUCTS_BY_FILTER_ERROR';

export const GET_PRODUCTS_BY_CATEGORY = 'products/GET_PRODUCTS_BY_CATEGORY';
export const GET_PRODUCTS_BY_CATEGORY_LOADING = 'products/GET_PRODUCTS_BY_CATEGORY_LOADING';
export const GET_PRODUCTS_BY_CATEGORY_ERROR = 'products/GET_PRODUCTS_BY_CATEGORY_ERROR';
